# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/Hugo.gitlab-ci.yml

---
#
# Before using this .gitlab-ci.yml:
#
# - This example uses the latest Docker image, but you might want to use the
#   exact version to avoid any broken pipelines.
#   All available Hugo versions are listed under https://gitlab.com/pages/hugo/container_registry.
# - Read about the difference between hugo and hugo_extended
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#hugo-vs-hugo_extended.
#   If you don't know what to use, better use the extended version.
# - To change the theme, see
#   https://gitlab.com/pages/hugo/-/blob/main/README.md#use-a-custom-theme.
#

workflow:
  # Avoid duplicate pipelines for merge requests (for pushes and merge requests)
  # See: https://docs.gitlab.com/ci/yaml/workflow/#switch-between-branch-pipelines-and-merge-request-pipelines
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH

default:
  image: hugomods/hugo:exts-0.147.0

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  HUGO_ENV: production
  GIT_DEPTH: 1

test:
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - npm run build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH && $CI_PIPELINE_SOURCE != "merge_request_event"
  cache:
    - key: npm-cache-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - npm-cache-$CI_DEFAULT_BRANCH
        - npm-cache-default
      paths:
        - .npm/

# Artifact will be deployed to https://beta.xenproject.org/
deploy:
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - npm run build -- -- --baseURL "https://beta.xenproject.org/"
    - tar caf site.tar.gz public
  artifacts:
    paths:
      - site.tar.gz
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  cache:
    - key: npm-cache-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - npm-cache-$CI_DEFAULT_BRANCH
        - npm-cache-default
      paths:
        - .npm/

# Artifact will be published to https://xenproject.org/
publish:
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint
    - node scripts/downloads/getLinks.js
    - npm run build -- -- --baseURL "https://xenproject.org/"
    - tar caf site.tar.gz public
  artifacts:
    paths:
      - site.tar.gz
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  cache:
    - key: npm-cache-$CI_COMMIT_REF_SLUG
      fallback_keys:
        - npm-cache-$CI_DEFAULT_BRANCH
        - npm-cache-default
      paths:
        - .npm/
